### ISSUE TITLE
Exclude Bots In the 'Who's Online'

### ISSUE THREAD

**Issue by SerpiusCapricornus** [mybbgroup/iPatrol#10]
Is it possible to add an option in the AdminCP to exclude bots that the iPatrol approves?

View the screenshot link.

[https://i.gyazo.com/bebcb14ea3dd63db7089d2662f3266b3.png](url)

**Comment by effone** [comment]
No point hooking into WOL and mess with listing.
Not at all something this plugin is focused to...

**Comment by SerpiusCapricornus** [comment]
Like I said... it's silly for iPatrol to list all of the approved bots in the listing as shown in the screenshot link below. 

If this is something that will not be optional, then I will not run this plugin.

[https://i.gyazo.com/c7bb4e2ce32a4c0a44a949995993f080.png](url)

**Comment by Eldenroot** [comment]
It is not a feature for this plugin, it is inbuild MyBB core feature to display bots in who is online page. iPatrol just adds new bots into the DB to make life easier for bots and make your site "better" for searches.

It is fully up to you to not use this plugin for something what is not in our direction, it would need another plugin or a core modification.

**Comment by effone** [comment]
If you don't want to list down spiders in WOL list then another option is to use a simple plugin that will hide all spider names only showing the count. Sounds fair?

**Comment by Eldenroot** [comment]
@SerpiusCapricornus - you can always disable this feature in iPatrol...

anyway here is a workaround
https://community.mybb.com/thread-188357-post-1205260.html#pid1205260

**Comment by SerpiusCapricornus** [comment]
Are you talking about this modification to the 'online.php'?

As shown in the screenshot?

[https://i.gyazo.com/b33083c4d5bb2f89af15212c9da8ccc3.png](url)
