### ISSUE TITLE
Uncaught Error: Call to undefined function ipatrol_ban_regdupe()

### ISSUE THREAD

**Issue by platise** [mybbgroup/iPatrol#19]
Hi,

I've installed iPatrol (besides it I have the "Disposable Email Blacklist (merging of Depressurize and Stardust342 plugins) (3.0)" plugin), and encountered error: I am using PHP 7.3.

~~~~~~~~~~~~~~~~
*204788 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ipatrol_ban_regdupe() in /../inc/class_plugins.php:142
Stack trace:
#0 /../member.php(95): pluginSystem->run_hooks(Array)
#1 {main}
~~~~~~~~~~~~~~~~

Best regards,
Uros

**Comment by effone** [comment]
The said function is planned and was there commented for some while.
Comment out / delete this hook in plugin file at line 290, no idea how but this line remained there:

`$plugins->add_hook('member_do_register_start', 'ipatrol_ban_regdupe');`

**Comment by platise** [comment]
Thank you for prompt reply. Removed it and it works.
