### ISSUE TITLE
Users cannot register

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/iPatrol#22]
![image](https://user-images.githubusercontent.com/778890/71748259-3cd59080-2e72-11ea-95c6-b67a21926232.png)

summon @effone

**Comment by KrysisDK** [comment]
Has not been fixed yet. I'm also getting this error as of today.

**Comment by AlekzNet** [comment]
Indeed, same issue.

**Comment by effone** [comment]
This was already been fixed by PR #20 
https://github.com/mybbgroup/iPatrol/pull/20/files

Please use the latest repo version or just make sure this line is commented out / removed at line 290
`$plugins->add_hook('member_do_register_start', 'ipatrol_ban_regdupe');`

**Comment by Eldenroot** [comment]
I dont think so... I use the latest repo version and I had same issue (many reports from users)

**Comment by effone** [comment]
Please check once more.
