### ISSUE TITLE
how to disable private message from iPatrol?

### ISSUE THREAD

**Issue by hzkincony** [mybbgroup/iPatrol#29]
i have installed iPatrol,  but it will send many detected private message to me. it showed "You have 229 unread private messages. The most recent is from admin titled New spider visit detected"  every minute will receive private message, whether can disable it?

**Comment by MattyWjeisz** [comment]
There is an option in settings - 'Send PM Notifications'. Select 'No'.

**Comment by effone** [comment]
There is already a setting available to disable PM notifications.
