### ISSUE TITLE
Version Is Incorrect

### ISSUE THREAD

**Issue by SerpiusCapricornus** [mybbgroup/iPatrol#4]
[https://i.gyazo.com/5f4ff7b86f84eab54e22cf755d10978d.png](url)

The version is incorrect... it shows the word 'Alpha' in the version when you see it listed in the Plugins section of the AdminCP.

(not certain if the screenshot link will show up in here)

**Comment by Eldenroot** [comment]
It is a first public preview... when we reach out of that phase we will change the version number...

**Comment by SerpiusCapricornus** [comment]
Oh?

I was assuming that if it is a public release, then it must be out of the 'Alpha' stage. 
Usually, I see software releases as 'Alpha', which most of the time is not released to the public. (most of the time it's kept "in-house" for testing purposes)
Then, the 'Beta' is released and available to the public for further testing.  

Maybe, I am wrong on this?   ¯\_(ツ)_/¯

**Comment by Eldenroot** [comment]
Actually it depends on developers... 

This plugin is quite complex and we need to test every circumstances and settings. We cannot guarantee that all will be working for 100% out of the box. More users = more testers = better product. Thats why we released it as a first public preview to cover all issues. Anyway plugin had been tested for 2 months on our live board without any issue. If anything let us know, there is a list of planned features, feel free to share your idea :)

**Comment by SerpiusCapricornus** [comment]
So far, it's working well!!

I have the plugin running for about 45 minutes and it has banned 2 IP addresses due to being listed on an IP Blacklist. 

It has cleared 22 spiders as legit IPs. 

That's very nice!!!

**Comment by effone** [comment]
Its always good to see positive feedback.
Thanks for testing @SerpiusCapricornus
