### ISSUE TITLE
Where Is The iPatrol Info On User IPs?

### ISSUE THREAD

**Issue by SerpiusCapricornus** [mybbgroup/iPatrol#5]
I am looking for specific user information on IPs, but I do not see it in the ModCP.

This is a quote from the plugin release... "Track the location of your visitor and get various informations like: Country, City, Region, District, Timezone, Zipcode, Latitude-Longitude, Service Provider and many more."

Where would that information be located?

Would that be in the ModCP? I do not see it as shown in the screenshot.

[https://i.gyazo.com/52b257af0e09626a36ed7e32cd54dcbc.png](url)

**Comment by effone** [comment]
Visit who's online page. `[Locate]` is available there only. Atleast for now.

**Comment by SerpiusCapricornus** [comment]
Ok... I did check this and this is what I saw... in the screenshot. (using the colorized MyBB default theme)

I don't see any iPatrol information in there. 

Am I doing something wrong?

[https://i.gyazo.com/1cc44944997f766f7ce305b32d09331c.png](url)

**Comment by effone** [comment]
The attached snap clearly shows there is an additional link `[Locate] ` apart from the default `[Lookup] ` beside every IP which has been added by iPatrol.

**Comment by SerpiusCapricornus** [comment]
Aha! That can be easily missed! 

Now that I re-read your first response... yea, [Locate] is there.

I think... for the future... somewhere in your documentation, it should be clearly stated that if a Staff person wants to view this without using the ModCP, they can use the [Locate] function within the Who's Online page.

Otherwise, if you had not told me exactly where to look for this... I am fairly certain that many staff people will oversee and miss that [Locate] function.

**Comment by effone** [comment]
Noted.
