### ISSUE TITLE
Whitelist Feature for False Positive On IP Ban

### ISSUE THREAD

**Issue by SerpiusCapricornus** [mybbgroup/iPatrol#6]
I am double checking ALL banned IPs by iPatrol and this one may be a 'false positive' for a banned IP.

89.238.167.86

Check the link below...

[https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a89.238.167.86&run=toolpage](url)

If this is proven to be a legit IP address, then it might be wise to add a 'whitelist' feature for iPatrol for situations such as this.

**Comment by effone** [comment]
Noted.
iPatrol relies on the third party API and acts as per the result returned.
The whitelist feature will be added.

**Comment by SerpiusCapricornus** [comment]
If possible... in the 'Whitelist' feature, please allow admins to 'Copy & Paste' a list of legit IPs from Notepad or similar text editors because that whitelist can grow pretty quickly in a 24 hour period.
I have already verified another 'false positive' IP.

**Comment by effone** [comment]
It will be a textbox in settings.
