### ISSUE TITLE
Location Details Box Is Too Low & Second Details Box Does Not Overwrite First Box

### ISSUE THREAD

**Issue by SerpiusCapricornus** [mybbgroup/iPatrol#7]
Two issues in one...

As shown in the screenshot... (using colorized default MyBB theme)

First issue...
I clicked on the 'Locate' beside my username, then I clicked on the user 'James' and his 'Location Details' box did not overwrite my 'Location Details' box. If the overwrite does not work and if the admin tries to do multiple 'Location Details' boxes, it can go way over to the right side of the screen, thus making viewing of those boxes difficult.

Second issue...
The 'Location Details' box is being shown WAY TOO LOW and part of the information is blocked out.

[https://i.gyazo.com/f4c72921b2e195b9f4bc236206b6d698.png](url)

**Comment by effone** [comment]
It should be a modal at the first place.
The modal initiation broke and its a known issue with current MyBB modal. 
It happens at random. 
Try this patch:
https://mybb.group/Thread-MyBB-Modal-Appearance-Fix

**Comment by SerpiusCapricornus** [comment]
Yes! That little code change fixed the modal issue.

The screenshot shows this as the correct way to view this.

[https://i.gyazo.com/b286aa1de689580f9b451762fb34e688.png](url)

**Comment by SerpiusCapricornus** [comment]
**Addendum:**

My other custom themes are able to show the 'Location Details' AFTER the patch was applied.

Prior to the patch being applied, neither one of my custom themes were able to show any 'Location Details' windows. 

This will be an important patch to apply to the MyBB code to make this plugin and possibly other plugins to properly show the appropriate window popups.

**Comment by effone** [comment]
Not only plugins. This malfunctions in many case and functions of native MyBB, like reputation or buddy list. Thing is it happens at random, I have tested whos online locate in a default theme without the patch. Sometimes it works, sometimes doesn't.
